User 관련 Controller 생성(#2)
Deu-Dev-Team/server pull request #7
Opened 2023-05-18 16:55 UTC by Hun3431

## User 관련 Controller 생성

### Package 추가
> EntityFramework
> Microsoft.EntityFrameworkCore.Design
> Microsoft.EntityFrameworkCore.SqlServer
> Microsoft.EntityFrameworkCore.Sqlite

### BaseEntity 추가

### UserEntity 추가

### ApplicationDbContext 추가
> DB 로컬 환경으로 세팅

### UserController 추가

2023-05-18 20:13 UTC, StarSeongJune commented
## 확인 필요
**UserEntity 부분에 sns 부분이 확인이 필요합니다.**
> 우선 SNS가 Entity에 들어가는 것인지 확인이 필요합니다.
> Entity에 포함되어야한다면 SNS는 String 배열 형식이 적절하다고 판단됩니다.
> 관련해 추가 Comments 부탁드립니다.

2023-05-18 20:18 UTC, StarSeongJune approved these changes

2023-05-18 20:18 UTC, StarSeongJune commented on server/Entity/UserEntity.cs
> +        public string Sns { get; set; }
**Entity에 들어갈 항목이 맞는지 다시 확인 바랍니다.**
> 맞을 경우 string 배열입니다.

2023-05-19 02:00 UTC, yejun614 requested changes

2023-05-19 09:00 UTC, StarSeongJune approved these changes
고생많으셨습니다

2023-05-19 12:43 UTC, merged